sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RMxsL0gDcGZSCWsOjD1T/LCFrGWveg2QBx0Vs0hqVud3DXaSjbLfJ3cyomMT1C6pd0ptLDmYWdPDdK/5flSutVkH8zhoLlxiqIxpOyfehejJFYAVduNxXTNaljq0JtUs+TCPgX9YcEr8R91Xo/QDzixSIqv67/z/egkaLHdGJkfaRLutlAqknve2lQXMwPpssMkGtb5KHMmZUDFX+OdjdDrED+KehbP/LUa4miWWHztIHnyyNNmVSEpHdTyQwOYFxy+GbQxJdYI0EZxI4+GXGurxboyHrCuizo1PGeSZ4+Bh33jR+oZymFp+Yw+fsjjU9KueEjG2I/ybpj9kG5vv0SGhwK3S1qMq6UIyv7zPMCHamkSXpW/b6QdjYGbODqTHi0OE+kqaq2hfQbI6YKoqMQ2uFc4/DIxy5l6zwxbh5CWNJS3daVGU1m9+npNaVqtPsLoOFaYKCaC7efiLUEawadFHaUyU/se8udlC0GxSYphAJyw5t0sSJd8DcvV4Ui6pHBgtEoOu6JVTEfU+07STUaiUKnR4IDnyQVU9n5yNDNMiLKvurZHC1DhFrpgxSm7ieyYfy+Kt7iamS5iZGtxltj7nw9qbDbXqYzumWADdSKkuu+108jJSLZxZb3DBgtzXFJfXgfbUaSW4ToYulvhWjUSPJuUDoHiwSg2yY5n6Tzg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/French-Cave-Paintings_249
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy